Repository dnd-side-project/dnd-9th-1-ios, pull requests merged in 2023-08, with the labels that each got.

#6 [#5] 프로젝트 세팅 완료
  .gitignore
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Milestone/Milestone.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Milestone/Milestone.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Milestone/Milestone/Global/Base/BaseCollectionViewCell.swift
  Milestone/Milestone/Global/Base/BaseTableViewCell.swift
  Milestone/Milestone/Global/Base/BaseViewController.swift
  Milestone/Milestone/Global/Extension/Data+.swift
  Milestone/Milestone/Global/Extension/Encodable+.swift
  Milestone/Milestone/Global/Extension/NSObject+.swift
  Milestone/Milestone/Global/Extension/UICollectionView+.swift
  Milestone/Milestone/Global/Extension/UIColor+.swift
  Milestone/Milestone/Global/Extension/UIFont+.swift
  Milestone/Milestone/Global/Extension/UIImage+.swift
  Milestone/Milestone/Global/Extension/UILabel+.swift
  Milestone/Milestone/Global/Extension/UITableView+.swift
  Milestone/Milestone/Global/Extension/UIView+.swift
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/stone.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/stone.imageset/stone.svg
  Milestone/Milestone/Global/Resource/Base.lproj/LaunchScreen.storyboard
  Milestone/Milestone/Global/Resource/Font/Pretendard-Black.otf
  Milestone/Milestone/Global/Resource/Font/Pretendard-Bold.otf
  Milestone/Milestone/Global/Resource/Font/Pretendard-ExtraBold.otf
  Milestone/Milestone/Global/Resource/Font/Pretendard-ExtraLight.otf
  Milestone/Milestone/Global/Resource/Font/Pretendard-Light.otf
  Milestone/Milestone/Global/Resource/Font/Pretendard-Medium.otf
  Milestone/Milestone/Global/Resource/Font/Pretendard-Regular.otf
  Milestone/Milestone/Global/Resource/Font/Pretendard-SemiBold.otf
  Milestone/Milestone/Global/Resource/Font/Pretendard-Thin.otf
  Milestone/Milestone/Global/Support/AppDelegate.swift
  Milestone/Milestone/Global/Support/Info.plist
  Milestone/Milestone/Global/Utils/Logger.swift
  Milestone/Milestone/Network/Foundation/APIEnvironment.swift
  Milestone/Milestone/Network/Foundation/APIError.swift
  Milestone/Milestone/Network/Foundation/APIService.swift
  Milestone/Milestone/Network/Foundation/BaseModel.swift
  Milestone/Milestone/Network/Foundation/NetworkStatus.swift
  Milestone/Milestone/Network/Foundation/Requestable.swift
  Milestone/Milestone/Screens/Onboarding/ViewController.swift
  Milestone/MilestoneTests/MilestoneTests.swift
  Milestone/MilestoneUITests/MilestoneUITests.swift
  Milestone/MilestoneUITests/MilestoneUITestsLaunchTests.swift
Labels: chore, seori

#7 [#3] swiftlint 적용
  Milestone/.swiftlint.yml
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Extension/UIColor+.swift
  Milestone/Milestone/Global/Extension/UILabel+.swift
  Milestone/Milestone/Global/Extension/UIView+.swift
  Milestone/Milestone/Global/Support/AppDelegate.swift
Labels: style, jun

#9 [#8] UIColor 색상 추가
  Milestone/Milestone/Global/Extension/UIColor+.swift
Labels: chore, jun

#10 [#5] Team과 bundle identifier 설정
  Milestone/Milestone.xcodeproj/project.pbxproj
Labels: chore, seori

#12 [#11] 로그인 뷰 제작
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Base/BaseViewController.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/Milestone.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/Milestone.imageset/Milestone.png
  Milestone/Milestone/Global/Resource/Assets.xcassets/appleLogo_black.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/appleLogo_black.imageset/appleLogo_black.png
  Milestone/Milestone/Global/Resource/Assets.xcassets/kakaoLogo.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/kakaoLogo.imageset/kakaoLogo.png
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding_1.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding_1.imageset/onboarding_1.png
  Milestone/Milestone/Global/Support/AppDelegate.swift
  Milestone/Milestone/Screens/Onboarding/View/LoginViewController.swift
Labels: feat

#14 [#13] 메인 헤더와 채움함 화면 구현
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Extension/UIButton+.swift
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/calendar.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/calendar.imageset/calendarImg.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/plus.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/plus.imageset/plusBtn.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/setting.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/setting.imageset/setting.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/tempGoal.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/tempGoal.imageset/tempGoal.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/tempStone.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/tempStone.imageset/tempImg.svg
  Milestone/Milestone/Global/Support/AppDelegate.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/ParentGoalHeaderView.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/ParentGoalTableViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/View/GoalStatusView.swift
  Milestone/Milestone/Screens/Main/View/MainSegmentedControl.swift
  Milestone/Milestone/Screens/Main/View/MainViewController.swift
  Milestone/Milestone/Screens/StorageBox/View/StorageBoxViewController.swift
Labels: feat, seori

#19 [#18] 소셜로그인 버튼 폰트 수정
  Milestone/Milestone/Screens/Onboarding/View/LoginViewController.swift
Labels: jun, fix

#21 [#20] BaseViewController viewDidLoad 함수 내부 호출순서 수정
  Milestone/Milestone/Global/Base/BaseViewController.swift
  Milestone/Milestone/Screens/Main/View/MainViewController.swift
  Milestone/Milestone/Screens/Onboarding/View/LoginViewController.swift
Labels: jun, fix

#22 [#17] 메인 화면에 NavigationController 추가
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/feat-issue-template.md
  Milestone/Milestone/Global/Extension/UIColor+.swift
  Milestone/Milestone/Global/Support/AppDelegate.swift
  Milestone/Milestone/Screens/Main/View/MainViewController.swift
Labels: feat, seori

#23 [#2] 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/feat-issue-template.md
Labels: chore, seori

#25 [#16] 온보딩 화면 구현 및 코디네이터 패턴 적용 & 문서화
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Extension/NSMutableAttributedString+.swift
  Milestone/Milestone/Global/Extension/UIColor+.swift
  Milestone/Milestone/Global/Extension/UILabel+.swift
  Milestone/Milestone/Global/Extension/UITextField+.swift
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding2.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding2.imageset/onboarding2.png
  Milestone/Milestone/Global/Support/AppCoordinator.swift
  Milestone/Milestone/Global/Support/AppDelegate.swift
  Milestone/Milestone/Global/Support/Coordinator.swift
  Milestone/Milestone/Screens/Onboarding/OnboardingCoordinator.swift
  Milestone/Milestone/Screens/Onboarding/View/LoginViewController.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingViewController.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingViewControllerLast.swift
  Milestone/Milestone/Screens/Onboarding/ViewController.swift
Labels: feat, jun

#31 [#15] 상위 목표 상세 보기 화면 구현
  .github/ISSUE_TEMPLATE/feat-issue-template.md
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Base/BaseCollectionViewCell.swift
  Milestone/Milestone/Global/Base/BaseTableViewCell.swift
  Milestone/Milestone/Global/Base/BaseViewController.swift
  Milestone/Milestone/Global/Extension/UIColor+.swift
  Milestone/Milestone/Global/Extension/UIView+.swift
  Milestone/Milestone/Global/Extension/UIViewController+.swift
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/addStone.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/addStone.imageset/addStone.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/blueCheck.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/blueCheck.imageset/blueCheck.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone1.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone1.imageset/completedStone1.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone2.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone2.imageset/completedStone2.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone3.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone3.imageset/completedStone3.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone4.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone4.imageset/completedStone4.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone5.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone5.imageset/completedStone5.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone6.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone6.imageset/completedStone6.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone7.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone7.imageset/completedStone7.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone8.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone8.imageset/completedStone8.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone9.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/completedStone9.imageset/completedStone9.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone1.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone1.imageset/detailStone1.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone2.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone2.imageset/detailStone2.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone3.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone3.imageset/detailStone3.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone4.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone4.imageset/detailStone4.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone5.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone5.imageset/detailStone5.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone6.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone6.imageset/detailStone6.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone7.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone7.imageset/detailStone7.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone8.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone8.imageset/detailStone8.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone9.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/detailStone9.imageset/detailStone9.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/whiteCheck.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/whiteCheck.imageset/whiteCheck.svg
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/Model/DetailGoal.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/DetailGoalCollectionViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/DetailGoalTableViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/View/MoreOptionView.swift
  Milestone/Milestone/Screens/FillBox/View/MoreViewController.swift
Labels: feat, seori

#36 [#35] 공통 뷰모델 프로토콜 정의
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Base/ViewModelBindableType.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/CompletionBox/ViewModel/CompletionViewModel.swift
  Milestone/Milestone/Screens/Main/View/MainViewController.swift
Labels: feat, jun

#37 [#28] 세부 목표 정보 팝업 뷰 구현
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/alarm.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/alarm.imageset/alarm.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/xmark.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/xmark.imageset/xmark.svg
  Milestone/Milestone/Screens/FillBox/View/DetailGoalInfoView.swift
  Milestone/Milestone/Screens/FillBox/View/DetailGoalInfoViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
Labels: feat, seori

#41 [#40] 스플래쉬 화면 구현
  Milestone/Milestone/Global/Resource/Assets.xcassets/splashLogo.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/splashLogo.imageset/splashLogo.svg
  Milestone/Milestone/Global/Resource/Base.lproj/LaunchScreen.storyboard
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
Labels: feat, seori

#42 [#39] 완료함 메인 구현
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/alert.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/alert.imageset/alert.png
  Milestone/Milestone/Global/Resource/Assets.xcassets/placeholder.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/placeholder.imageset/placeholder.png
  Milestone/Milestone/Screens/CompletionBox/View/Cell/CompletionTableViewCell.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionAlertView.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/TriangleView.swift
  Milestone/Milestone/Screens/CompletionBox/ViewModel/CompletionViewModel.swift
Labels: feat, jun

#47 [#43] 완료함 메인뷰 to 마일이 질문받기 뷰 제작
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Base/BaseViewController.swift
  Milestone/Milestone/Global/Extension/UITextField+.swift
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/afterSelected1.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/afterSelected1.imageset/afterSelected1.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/afterSelected2.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/afterSelected2.imageset/afterSelected2.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/afterSelected3.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/afterSelected3.imageset/afterSelected3.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/afterSelected4.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/afterSelected4.imageset/afterSelected4.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/afterSelected5.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/afterSelected5.imageset/afterSelected5.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/beforeSelected1.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/beforeSelected1.imageset/beforeSelected5.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/beforeSelected2.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/beforeSelected2.imageset/beforeSelected4.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/beforeSelected3.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/beforeSelected3.imageset/beforeSelected3.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/beforeSelected4.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/beforeSelected4.imageset/beforeSelected2.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/beforeSelected5.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/beforeSelected5.imageset/beforeSelected1.svg
  Milestone/Milestone/Screens/CompletionBox/CompletionBoxCoordinator.swift
  Milestone/Milestone/Screens/CompletionBox/View/Cell/CompletionTableViewCell.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewWithGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewWithoutGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/IndexView.swift
  Milestone/Milestone/Screens/CompletionBox/View/PointView.swift
  Milestone/Milestone/Screens/CompletionBox/View/TriangleView.swift
  Milestone/Milestone/Screens/CompletionBox/ViewModel/CompletionViewModel.swift
Labels: feat, jun

#53 [#45] 채움함의 툴팁 기능 구현
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/bubbleTail.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/bubbleTail.imageset/bubbleTail.svg
  Milestone/Milestone/Screens/FillBox/View/BubbleView.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
Labels: feat, seori

#54 [#46] 상위 목표 상세 화면의 코치 마크 뷰 구현
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/mile.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/mile.imageset/mile.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/whiteBigX.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/whiteBigX.imageset/whiteBigX.svg
  Milestone/Milestone/Screens/FillBox/View/AddDetailGoalStoneView.swift
  Milestone/Milestone/Screens/FillBox/View/CouchMarkViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
Labels: feat, seori

#55 [#51] 회고 완료뷰 제작 마무리
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/close.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/close.imageset/close.svg
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewWithoutGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/PointView.swift
  Milestone/Milestone/Screens/CompletionBox/View/ReviewCompleteView.swift
  Milestone/Milestone/Screens/CompletionBox/View/ReviewCompleteViewController.swift
Labels: feat, jun

#57 [#56] 회고 보기 뷰 구현
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewWithoutGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithoutGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/IndexViewAfterSaved.swift
  Milestone/Milestone/Screens/CompletionBox/ViewModel/CompletionViewModel.swift
Labels: feat, jun

#65 [#62] 목표 삭제 팝업 뷰 구현
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Screens/FillBox/View/AskOneOfTwoView.swift
  Milestone/Milestone/Screens/FillBox/View/DeleteGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailGoalInfoView.swift
  Milestone/Milestone/Screens/FillBox/View/DetailGoalInfoViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/View/MoreViewController.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingViewController.swift
Labels: feat, seori

#72 [#68] Enum과 Component, Protocol 폴더를 생성하여 파일 구조를 정리
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Component/CompletionBox/CompletionAlertView.swift
  Milestone/Milestone/Global/Component/CompletionBox/IndexView.swift
  Milestone/Milestone/Global/Component/CompletionBox/IndexViewAfterSaved.swift
  Milestone/Milestone/Global/Component/CompletionBox/PointView.swift
  Milestone/Milestone/Global/Component/CompletionBox/TriangleView.swift
  Milestone/Milestone/Global/Component/FillBox/AddDetailGoalStoneView.swift
  Milestone/Milestone/Global/Component/FillBox/DetailGoalInfoView.swift
  Milestone/Milestone/Global/Component/FillBox/EnterGoalAlarmView.swift
  Milestone/Milestone/Global/Component/FillBox/GoalStatusView.swift
  Milestone/Milestone/Global/Component/FillBox/MoreOptionView.swift
  Milestone/Milestone/Global/Component/General/AskOneOfTwoView.swift
  Milestone/Milestone/Global/Component/General/BubbleView.swift
  Milestone/Milestone/Global/Component/General/CompleteView.swift
  Milestone/Milestone/Global/Component/General/EnterGoalDateView.swift
  Milestone/Milestone/Global/Component/General/EnterGoalTitleView.swift
  Milestone/Milestone/Global/Component/General/ReminderAlarmView.swift
  Milestone/Milestone/Global/Component/General/RoundedDarkButton.swift
  Milestone/Milestone/Global/Component/Main/MainSegmentedControl.swift
  Milestone/Milestone/Global/Enum/ButtonStateStyle.swift
  Milestone/Milestone/Global/Enum/DayStyle.swift
  Milestone/Milestone/Global/Enum/IndexTextStyle.swift
  Milestone/Milestone/Global/Enum/PointTextStyle.swift
  Milestone/Milestone/Global/Enum/UserDefaultsKeyStyle.swift
  Milestone/Milestone/Global/Enum/WriteRetrospectStyle.swift
  Milestone/Milestone/Global/Support/Coordinator.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewWithGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewWithoutGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/ViewModel/CompletionViewModel.swift
  Milestone/Milestone/Screens/FillBox/Protocol/PresentDelegate.swift
  Milestone/Milestone/Screens/FillBox/Protocol/UpdateButtonStateDelegate.swift
  Milestone/Milestone/Screens/FillBox/View/AddDetailGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/AddParentGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingViewController.swift
Labels: style, chore, seori

#67 [#66] 채움함 하단의 플로팅 버튼 클릭 스타일 변경
  Milestone/Milestone/Global/Extension/UIButton+.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
Labels: seori, fix

#74 [#73] 완료함의 말풍선 뷰를 BubbleView 컴포넌트로 교체
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
Labels: refactor, seori

#76 [#75] 세부 목표 정보 팝업 뷰에서 startDateLabel 제거 후 레이아웃 수정
  Milestone/Milestone/Global/Component/FillBox/DetailGoalInfoView.swift
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Screens/FillBox/View/DetailGoalInfoViewController.swift
Labels: seori, fix

#85 [#84] UISwitch의 off 시 배경색을 검정색에서 디폴트로 변경
  Milestone/Milestone/Global/Component/General/ReminderAlarmView.swift
Labels: seori, fix

#87 [#86] UserDefaults의 key 값으로 enum을 적용하여 코드 개선
  Milestone/Milestone/Global/Enum/UserDefaultsKeyStyle.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
Labels: refactor, seori

#89 [#88] 설정 버튼 클릭 스타일 변경
  Milestone/Milestone/Screens/Main/View/MainViewController.swift
Labels: seori, fix

#71 [#70] 목표 달성 비율에 맞춰 원 그리기
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Screens/FillBox/View/Cell/ParentGoalTableViewCell.swift
  Milestone/Milestone/Screens/Shared/GoalAchievementRateView.swift
Labels: feat, jun

#79 [#78] 키체인 매니저 CRUD 구현 및 Rx 커스텀 익스텐션 연동
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Utils/KeychainManager.swift
Labels: feat, jun

#95 [#77] 목표 수정 화면 완료 (상위 목표, 세부 목표 다)
  Milestone/Milestone/Global/Component/FillBox/DetailGoalInfoView.swift
  Milestone/Milestone/Global/Component/General/EnterGoalTitleView.swift
  Milestone/Milestone/Global/Extension/UIViewController+.swift
  Milestone/Milestone/Screens/FillBox/View/AddParentGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailGoalInfoViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/View/MoreViewController.swift
Labels: feat, seori

#91 [#69] 마일이 일러스트 삽입
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/AppIcon.appiconset/appIcon.png
  Milestone/Milestone/Global/Resource/Assets.xcassets/retrospectComplete.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/retrospectComplete.imageset/reviewComplete.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/retrospectView1.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/retrospectView1.imageset/retrospectView.svg
  Milestone/Milestone/Screens/CompletionBox/View/Cell/CompletionTableViewCell.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithoutGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/ReviewCompleteViewController.swift
Labels: chore, jun

#100 [#94] png 에셋 svg로 업데이트
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Component/General/RoundedButton.swift
  Milestone/Milestone/Global/Component/General/RoundedDarkButton.swift
  Milestone/Milestone/Global/Enum/ButtonComponentStyle.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/alert.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/alert.imageset/alert.png
  Milestone/Milestone/Global/Resource/Assets.xcassets/alert.imageset/alert.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/completionEmptyImage.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/completionEmptyImage.imageset/completionEmptyImage.png
  Milestone/Milestone/Global/Resource/Assets.xcassets/completionEmptyImage.imageset/completionEmptyImage.svg
  Milestone/Milestone/Screens/FillBox/View/AddDetailGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/AddParentGoalViewController.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingViewController.swift
Labels: chore, jun

#96 [#90] 보관함 화면 구현 완료
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/emptyStorage.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/emptyStorage.imageset/emptyStorage.svg
  Milestone/Milestone/Screens/FillBox/Model/ParentGoal.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/ParentGoalTableViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/StorageBox/View/StorageBoxViewController.swift
Labels: feat, seori

#102 [#60] 네트워크 세팅
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone.xcodeproj/xcshareddata/xcschemes/Milestone.xcscheme
  Milestone/Milestone/Core/API/APIError.swift
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Core/API/APIService.swift
  Milestone/Milestone/Core/API/APISession.swift
  Milestone/Milestone/Core/Foundation/BindableViewModel.swift
  Milestone/Milestone/Core/Foundation/Lodable.swift
  Milestone/Milestone/Core/Services/Service.swift
  Milestone/Milestone/Core/Services/ServicesGoalList.swift
  Milestone/Milestone/Core/Services/ServicesUser.swift
  Milestone/Milestone/Global/Base/BaseModel.swift
  Milestone/Milestone/Global/Enum/GoalStatusParameter.swift
  Milestone/Milestone/Global/Utils/Constants.swift
  Milestone/Milestone/Model/DetailGoal.swift
  Milestone/Milestone/Model/Goal.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithoutGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/ViewModel/CompletionViewModel.swift
  Milestone/Milestone/Screens/FillBox/Model/DetailGoal.swift
  Milestone/Milestone/Screens/FillBox/View/AddParentGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/DetailGoalCollectionViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/DetailGoalTableViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/Onboarding/View/LoginViewController.swift
  Milestone/Milestone/Screens/StorageBox/View/StorageBoxViewController.swift
Labels: feat, jun

#103 [#97] 보관함의 상위 목표 상세 화면과 더보기 화면 구현
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Component/Shared/AskOneOfTwoView.swift
  Milestone/Milestone/Global/Component/Shared/BubbleView.swift
  Milestone/Milestone/Global/Component/Shared/CompleteView.swift
  Milestone/Milestone/Global/Component/Shared/EnterGoalDateView.swift
  Milestone/Milestone/Global/Component/Shared/EnterGoalTitleView.swift
  Milestone/Milestone/Global/Component/Shared/GoalAchievementRateView.swift
  Milestone/Milestone/Global/Component/Shared/ReminderAlarmView.swift
  Milestone/Milestone/Global/Component/Shared/RoundedButton.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/restore.imageset/restore.svg
  Milestone/Milestone/Screens/FillBox/View/Cell/DetailGoalCollectionViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/DetailGoalTableViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/View/MoreViewController.swift
  Milestone/Milestone/Screens/StorageBox/View/StorageBoxViewController.swift
Labels: feat, seori

#105 [#101] 카카오 로그인 구현 및 FCM 연동
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Milestone/Milestone.xcodeproj/xcshareddata/xcschemes/Milestone.xcscheme
  Milestone/Milestone/Core/API/APIIEventLogger.swift
  Milestone/Milestone/Core/API/APIInterceptor.swift
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Core/API/APISession.swift
  Milestone/Milestone/Core/Services/ServicesUser.swift
  Milestone/Milestone/Global/Enum/KeychainKeyList.swift
  Milestone/Milestone/Global/Extension/Data+.swift
  Milestone/Milestone/Global/Support/AppCoordinator.swift
  Milestone/Milestone/Global/Support/AppDelegate.swift
  Milestone/Milestone/Global/Support/GoogleService-Info.plist
  Milestone/Milestone/Global/Support/Info.plist
  Milestone/Milestone/Global/Utils/Constants.swift
  Milestone/Milestone/Global/Utils/KeychainManager.swift
  Milestone/Milestone/Milestone.entitlements
  Milestone/Milestone/Model/Token.swift
  Milestone/Milestone/Screens/Onboarding/View/LoginViewController.swift
  Milestone/Milestone/Screens/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: feat, jun

#109 [#104] 채움함 관련 ViewModel을 작성하고 데이터 바인딩
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Global/Base/ViewModelBindableType.swift
  Milestone/Milestone/Model/DetailGoal.swift
  Milestone/Milestone/Model/DetailGoalInfo.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/DetailGoalCollectionViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/DetailGoalTableViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailParentViewModel.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/FillBoxViewModel.swift
  Milestone/Milestone/Screens/Main/View/MainViewController.swift
  Milestone/Milestone/Screens/StorageBox/View/StorageBoxViewController.swift
Labels: refactor, seori

#112 [#106] 완료함 데이터 바인딩 및 API 연동
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Core/Services/ServicesGoalList.swift
  Milestone/Milestone/Global/Component/CompletionBox/IndexView.swift
  Milestone/Milestone/Global/Component/Shared/RoundedButton.swift
  Milestone/Milestone/Global/Enum/RewardToImage.swift
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/BLUE_JEWEL_2.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/BLUE_JEWEL_2.imageset/blueStoneVer2.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/GREEN_JEWEL_1.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/GREEN_JEWEL_1.imageset/greenStoneVer1.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/bad.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/bad.imageset/bad.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/book.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/book.imageset/book.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/gift.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/gift.imageset/gift.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/good.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/good.imageset/good.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/pen.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/pen.imageset/pen.svg
  Milestone/Milestone/Global/Utils/Constants.swift
  Milestone/Milestone/Model/CompletedGoal.swift
  Milestone/Milestone/Model/Goal.swift
  Milestone/Milestone/Screens/CompletionBox/View/Cell/CompletionHeaderView.swift
  Milestone/Milestone/Screens/CompletionBox/View/Cell/CompletionTableViewCell.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewWithGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithoutGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/ViewModel/CompletionViewModel.swift
Labels: feat, refactor, jun

#114 [#110] 채움함 상위 목표 목록 조회 API 연동
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/Services/ServicesGoalList.swift
  Milestone/Milestone/Model/Goal.swift
  Milestone/Milestone/Model/ParentGoal.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/CompletionBox/ViewModel/CompletionViewModel.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/FillBoxViewModel.swift
  Milestone/Milestone/Screens/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: feat, seori

#115 [#111] 상위 목표 상태별 개수 조회 API 연동 및 데이터 바인딩
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/Services/ServicesGoalList.swift
  Milestone/Milestone/Model/ParentGoal.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/FillBoxViewModel.swift
Labels: feat, seori

#121 [#116] 상위 목표 생성 API 연동
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Core/Services/ServicesGoalList.swift
  Milestone/Milestone/Global/Base/BaseModel.swift
  Milestone/Milestone/Global/Base/ViewModelBindableType.swift
  Milestone/Milestone/Model/ParentGoal.swift
  Milestone/Milestone/Screens/FillBox/Protocol/UpdateParentGoalListDelegate.swift
  Milestone/Milestone/Screens/FillBox/View/AddParentGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/AddParentGoalViewModel.swift
  Milestone/Milestone/Screens/Main/View/MainViewController.swift
Labels: feat, seori

#123 [#122] 세부 목표 리스트 조회 API 연동 및 뷰와 연결
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/Services/ServicesDetailGoal.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailParentViewModel.swift
Labels: feat, seori

#126 [#124] 세부 목표 생성 API 연동 완료
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/Services/ServicesDetailGoal.swift
  Milestone/Milestone/Global/Component/FillBox/EnterGoalAlarmView.swift
  Milestone/Milestone/Global/Enum/AMPMStyle.swift
  Milestone/Milestone/Global/Enum/DayStyle.swift
  Milestone/Milestone/Model/DetailGoalInfo.swift
  Milestone/Milestone/Screens/FillBox/Protocol/UpdateGoalListDelegate.swift
  Milestone/Milestone/Screens/FillBox/View/AddDetailGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/DetailGoalCollectionViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/AddDetailGoalViewModel.swift
Labels: feat, seori

#133 [#127] 세부 목표 완료 API 연동
  Milestone/Milestone/Core/Services/ServicesDetailGoal.swift
  Milestone/Milestone/Global/Base/BaseTableViewCell.swift
  Milestone/Milestone/Model/DetailGoal.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/DetailGoalTableViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailParentViewModel.swift
Labels: feat, seori

#134 [#128] 세부 목표 완료 취소 API 연동
  Milestone/Milestone/Core/Services/ServicesDetailGoal.swift
  Milestone/Milestone/Global/Base/BaseModel.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/ParentGoalTableViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailParentViewModel.swift
Labels: feat, seori

#137 [#99] 보관함 복구 뷰와 flow 구현
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Component/Shared/AskOneOfTwoView.swift
  Milestone/Milestone/Global/Component/Shared/RoundedButton.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/View/MoreViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailParentViewModel.swift
  Milestone/Milestone/Screens/StorageBox/View/ResetGoalViewController.swift
  Milestone/Milestone/Screens/StorageBox/View/RestoreGoalViewController.swift
  Milestone/Milestone/Screens/StorageBox/View/StorageBoxViewController.swift
Labels: feat, seori

#135 [#125] 설정화면 구현 및 푸시알람 설정
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Enum/UserDefaultsKeyStyle.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/LEVEL5.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/LEVEL5.imageset/LEVEL5.svg
  Milestone/Milestone/Screens/Main/View/MainViewController.swift
  Milestone/Milestone/Screens/Setting/Cell/SettingTableViewCellFirstSection.swift
  Milestone/Milestone/Screens/Setting/Cell/SettingTableViewCellSecondSection.swift
  Milestone/Milestone/Screens/Setting/SettingViewController.swift
Labels: feat, jun

#139 [#130] 상위 목표 삭제 API 연동
  Milestone/Milestone/Core/Services/ServicesGoalList.swift
  Milestone/Milestone/Global/Component/Shared/RoundedButton.swift
  Milestone/Milestone/Screens/FillBox/View/DeleteGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/View/MoreViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailParentViewModel.swift
  Milestone/Milestone/Screens/StorageBox/View/ResetGoalViewController.swift
Labels: feat, seori

#140 [#136] 설정화면 구현 및 401 에러 retry & adapt 함수 구현
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/API/APIInterceptor.swift
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Core/API/APISession.swift
  Milestone/Milestone/Core/Services/ServicesUser.swift
  Milestone/Milestone/Global/Component/Setting/InformationBox.swift
  Milestone/Milestone/Global/Component/Setting/InformationLabel.swift
  Milestone/Milestone/Global/Support/AppCoordinator.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/CompletionBox/ViewModel/CompletionViewModel.swift
  Milestone/Milestone/Screens/Onboarding/View/LoginViewController.swift
  Milestone/Milestone/Screens/Onboarding/ViewModel/OnboardingViewModel.swift
  Milestone/Milestone/Screens/Setting/PrivacyInformationViewController.swift
  Milestone/Milestone/Screens/Setting/SettingViewController.swift
Labels: feat, jun

#141 [#131] 세부 목표 상세 조회 API 연동
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Core/Services/ServicesDetailGoal.swift
  Milestone/Milestone/Global/Enum/DayStyle.swift
  Milestone/Milestone/Model/DetailGoal.swift
  Milestone/Milestone/Model/DetailGoalInfo.swift
  Milestone/Milestone/Screens/FillBox/View/AddDetailGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailGoalInfoViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/AddDetailGoalViewModel.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailParentViewModel.swift
Labels: feat, seori

#148 [#142] 세부 목표 수정 API 연동
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Core/Services/ServicesDetailGoal.swift
  Milestone/Milestone/Global/Component/FillBox/EnterGoalAlarmView.swift
  Milestone/Milestone/Model/DetailGoal.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/View/AddDetailGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailGoalInfoViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailParentViewModel.swift
Labels: feat, seori

#149 [#143] 세부 목표 삭제 API 연동
  Milestone/Milestone/Core/Services/ServicesDetailGoal.swift
  Milestone/Milestone/Model/DetailGoal.swift
  Milestone/Milestone/Screens/FillBox/View/DeleteGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailGoalInfoViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailParentViewModel.swift
Labels: feat, seori

#150 [#144] 상위 목표가 완료되는 시점에 목표 완료 팝업 뷰 띄우기
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Enum/JewelPopUpImageStyle.swift
  Milestone/Milestone/Screens/FillBox/View/CompleteGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailParentViewModel.swift
Labels: feat, seori

#151 [#147] 채움함 리스트 무한 스크롤 구현
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Core/Services/ServicesGoalList.swift
  Milestone/Milestone/Global/Utils/Constants.swift
  Milestone/Milestone/Screens/CompletionBox/ViewModel/CompletionViewModel.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/FillBoxViewModel.swift
Labels: feat, seori

#152 [#145] 보관함 목표 목록 조회 API 연동
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Screens/StorageBox/View/StorageBoxViewController.swift
  Milestone/Milestone/Screens/StorageBox/ViewModel/StorageBoxViewModel.swift
Labels: feat, seori

#153 [#146] 상위 목표 복구 API 연동
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Core/Services/ServicesGoalList.swift
  Milestone/Milestone/Global/Extension/UIViewController+.swift
  Milestone/Milestone/Model/Goal.swift
  Milestone/Milestone/Model/ParentGoal.swift
  Milestone/Milestone/Screens/FillBox/View/MoreViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailParentViewModel.swift
  Milestone/Milestone/Screens/StorageBox/View/ResetGoalViewController.swift
  Milestone/Milestone/Screens/StorageBox/View/RestoreGoalViewController.swift
  Milestone/Milestone/Screens/StorageBox/View/StorageBoxViewController.swift
Labels: feat, seori
