Repository dnd-side-project/dnd-9th-1-ios, pull requests merged in 2023-09, with the labels that each got.

#156 [#155] 상위 목표 데이터로 리마인드 여부 추가 및 뷰에 연결
  Milestone/Milestone/Model/ParentGoal.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewWithGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewWithoutGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithoutGuideViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/FillBox/View/MoreViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailParentViewModel.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/FillBoxViewModel.swift
  Milestone/Milestone/Screens/StorageBox/View/RestoreGoalViewController.swift
  Milestone/Milestone/Screens/StorageBox/ViewModel/StorageBoxViewModel.swift
Labels: seori, fix

#157 [#154] 보관함의 목표 랜덤 조회를 통해 목표 권유 기능 완성
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Core/Services/ServicesGoalList.swift
  Milestone/Milestone/Global/Component/FillBox/ContentSizedTableView.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/View/RecommendGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/FillBoxViewModel.swift
  Milestone/Milestone/Screens/Main/View/MainViewController.swift
Labels: feat, seori

#159 [#158] 목표 완료 팝업뷰의 완료함 가기 버튼, 목표 권유 팝업뷰의 보관함 가기 버튼 기능 구현
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Extension/Notification+.swift
  Milestone/Milestone/Screens/FillBox/View/CompleteGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/RecommendGoalViewController.swift
  Milestone/Milestone/Screens/Main/View/MainViewController.swift
Labels: feat, seori

#160 [#136] 로그인 관련 옵저버블 체이닝 로직 구현 / 화면전환 및 헤더 토큰세팅
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/API/APISession.swift
  Milestone/Milestone/Global/Enum/LoginType.swift
  Milestone/Milestone/Global/Utils/KeychainManager.swift
  Milestone/Milestone/Screens/Onboarding/View/LoginViewController.swift
  Milestone/Milestone/Screens/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: feat, jun

#164 [#163] API 요청 구조 수정 / 채움함 진행도 뷰 바인딩
  .gitignore
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Milestone/Milestone.xcodeproj/xcshareddata/xcschemes/Milestone.xcscheme
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/AppIcon.appiconset/appIcon.png
  Milestone/Milestone/Global/Support/AppDelegate.swift
  Milestone/Milestone/Global/Support/Info.plist
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/CompletionBox/ViewModel/CompletionViewModel.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/ParentGoalTableViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/FillBoxViewModel.swift
  Milestone/Milestone/Screens/Main/View/MainViewController.swift
Labels: feat, jun

#166 [#165] 채움함이 비었을 때 뜨는 뷰 구현
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Component/Shared/BubbleTailDownView.swift
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/bubbleTailDown.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/bubbleTailDown.imageset/bubbleTailDown.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/emptyFillBox.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/emptyFillBox.imageset/emptyFillBox.svg
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/FillBoxViewModel.swift
Labels: feat, seori

#171 [#169] navigation bar의 크기가 달라지는 버그 수정
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Component/Shared/DefaultLeftBarButton.swift
  Milestone/Milestone/Global/Utils/Constants.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithGuideViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionSavedReviewWithoutGuideViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
  Milestone/Milestone/Screens/Setting/PrivacyInformationViewController.swift
  Milestone/Milestone/Screens/Setting/SettingViewController.swift
Labels: bug, seori, fix

#175 [#174] 보관함 디데이 마이너스로 나오는 거 수정
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
Labels: bug, seori, fix

#177 [#176] 삭제할게요 버튼 스타일 변경
  Milestone/Milestone/Screens/FillBox/View/DeleteGoalViewController.swift
Labels: seori, fix

#172 [#168] 세부 목표 수정 결과가 뷰에 바로 적용되지 않는 버그 수정
  Milestone/Milestone/Screens/FillBox/View/DeleteGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailGoalInfoViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailParentViewController.swift
Labels: bug, seori, fix

#183 [#182] 온보딩 뷰 추가
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding3.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding3.imageset/onboarding3.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding4_1.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding4_1.imageset/onboarding4-1.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding4_2.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding4_2.imageset/onboarding4-2.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding5.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding5.imageset/onboarding5.svg
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding6.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/onboarding6.imageset/onboarding2.svg
  Milestone/Milestone/Screens/Onboarding/OnboardingCoordinator.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingSubviews/OnboardingViewControllerFirst.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingSubviews/OnboardingViewControllerFourth.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingSubviews/OnboardingViewControllerSecond.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingSubviews/OnboardingViewControllerThird.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingViewController.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingViewControllerLast.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingViewControllerTutorialFirst.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingViewControllerTutorialLast.swift
Labels: feat, jun

#185 [#184] 로그인 후 로딩상태에 따라 로티뷰 표시
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Milestone/Milestone/Global/Resource/Assets.xcassets/loading.dataset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/loading.dataset/loading.json
  Milestone/Milestone/Screens/Onboarding/View/LoginViewController.swift
  Milestone/Milestone/Screens/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: feat, jun

#188 [#186] 토스트뷰 컴포넌트 생성 및 에러처리
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Global/Component/Shared/ToastView.swift
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/warning.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/warning.imageset/warning.svg
  Milestone/Milestone/Screens/Onboarding/View/LoginViewController.swift
  Milestone/Milestone/Screens/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: feat, jun

#187 [#181] 세부 목표 키워드를 하위 목표로 변경 및 파일명 대거 수정
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Core/Services/ServicesDetailGoal.swift
  Milestone/Milestone/Core/Services/ServicesGoalList.swift
  Milestone/Milestone/Core/Services/ServicesLowerGoal.swift
  Milestone/Milestone/Global/Component/FillBox/AddLowerGoalStoneView.swift
  Milestone/Milestone/Global/Component/FillBox/LowerGoalInfoView.swift
  Milestone/Milestone/Global/Utils/Constants.swift
  Milestone/Milestone/Model/LowerGoal.swift
  Milestone/Milestone/Model/UpperGoal.swift
  Milestone/Milestone/Screens/CompletionBox/ViewModel/CompletionViewModel.swift
  Milestone/Milestone/Screens/FillBox/Protocol/UpdateGoalListDelegate.swift
  Milestone/Milestone/Screens/FillBox/View/AddLowerGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/AddUpperGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/LowerGoalCollectionViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/LowerGoalTableViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/ParentGoalHeaderView.swift
  Milestone/Milestone/Screens/FillBox/View/Cell/ParentGoalTableViewCell.swift
  Milestone/Milestone/Screens/FillBox/View/CompleteGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/CouchMarkViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DeleteGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailUpperViewController.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/FillBox/View/LowerGoalInfoViewController.swift
  Milestone/Milestone/Screens/FillBox/View/MoreViewController.swift
  Milestone/Milestone/Screens/FillBox/View/RecommendGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/DetailUpperViewModel.swift
  Milestone/Milestone/Screens/FillBox/ViewModel/FillBoxViewModel.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingViewControllerTutorialFirst.swift
  Milestone/Milestone/Screens/Onboarding/ViewModel/OnboardingViewModel.swift
  Milestone/Milestone/Screens/StorageBox/View/ResetGoalViewController.swift
  Milestone/Milestone/Screens/StorageBox/View/RestoreGoalViewController.swift
  Milestone/Milestone/Screens/StorageBox/View/StorageBoxViewController.swift
  Milestone/Milestone/Screens/StorageBox/ViewModel/StorageBoxViewModel.swift
Labels: seori, fix

#190 [#189] 카카오 네이티브 앱 키 세팅 / touchesBegan 추가 / 날짜 뷰 델리게이트 오타수정
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Screens/FillBox/View/AddLowerGoalViewController.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingViewControllerTutorialFirst.swift
Labels: bug, fix

#194 [#191] Fix 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/bug-report-template.md
Labels: docs, seori

#193 [#180] 네트워크 연결 실패 시 재시도 뷰 구현
  .github/ISSUE_TEMPLATE/bug-report-template.md
  Milestone/Milestone.xcodeproj/project.pbxproj
  Milestone/Milestone/Core/API/APIInterceptor.swift
  Milestone/Milestone/Core/API/APIRouter.swift
  Milestone/Milestone/Global/Component/FillBox/ContentSizedTableView.swift
  Milestone/Milestone/Global/Component/Shared/NetworkFailView.swift
  Milestone/Milestone/Global/Enum/AMPMStyle.swift
  Milestone/Milestone/Global/Enum/GoalStatusParameter.swift
  Milestone/Milestone/Global/Extension/UILabel+.swift
  Milestone/Milestone/Global/Literal/ImageLiteral.swift
  Milestone/Milestone/Global/Resource/Assets.xcassets/networkFail.imageset/Contents.json
  Milestone/Milestone/Global/Resource/Assets.xcassets/networkFail.imageset/networkFail.svg
  Milestone/Milestone/Global/Support/AppDelegate.swift
  Milestone/Milestone/Global/Utils/Constants.swift
  Milestone/Milestone/Global/Utils/KeychainManager.swift
  Milestone/Milestone/Global/Utils/NetworkMonitor.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionBoxViewController.swift
  Milestone/Milestone/Screens/CompletionBox/View/CompletionReviewWithoutGuideViewController.swift
  Milestone/Milestone/Screens/FillBox/Protocol/UpdateGoalListDelegate.swift
  Milestone/Milestone/Screens/FillBox/View/AddLowerGoalViewController.swift
  Milestone/Milestone/Screens/FillBox/View/DetailUpperViewController.swift
  Milestone/Milestone/Screens/FillBox/View/FillBoxViewController.swift
  Milestone/Milestone/Screens/Onboarding/View/LoginViewController.swift
  Milestone/Milestone/Screens/Onboarding/View/OnboardingSubviews/OnboardingViewControllerFourth.swift
  Milestone/Milestone/Screens/Setting/ViewModel/SettingViewModel.swift
  Milestone/Milestone/Screens/StorageBox/View/ResetGoalViewController.swift
  Milestone/Milestone/Screens/StorageBox/View/StorageBoxViewController.swift
Labels: feat, seori
